Dim booFlag as Boolean          
booFlag = True                  
Dim bytSmallInteger As Byte     
bytSmallInteger = 255           
Dim intMediumInteger As Integer 
intMediumInteger = -32768       
Dim lngLargeInteger As Long     
lngLargeInteger = 32768         
Dim sngSingleFP As Single       
sngSingleFP = 1.1               
Dim dblDoubleFP As Double       
dblDoubleFP = 1.00000001        
Dim strText As String           
strText = "Text"                
Print booFlag                   
Print bytSmallInteger           
Print intMediumInteger          
Print lngLargeInteger           
Print sngSingleFP               
Print dblDoubleFP               
Print strText                   
